# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 8eeba25
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: tooling
gitignore_dependencies: false
project_email: blake.naccarato+dev@gmail.com
project_name: dummy
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
year_of_project_creation: 2021
