# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 665ef69
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: tooling
gitignore_dependencies: false
project_email: dummy@dummy.dummy
project_name: dummy
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
tooling_tracking_repo: true
year_of_project_creation: 2021
