# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 18de4cb
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-latest
github_repo_name: copier-python-test
project_description: Example/test repo for blakeNaccarato/copier-python
project_email: blake.naccarato@gmail.com
project_name: copier_python_test
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
python_version: '3.11'
year_of_project_creation: 2022
