# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.0.2-22-ge97d377
_src_path: gh:blakeNaccarato/copier-python
github_repo_name: tooling
project_email: blake.naccarato+dev@gmail.com
project_name: dummy
project_owner_github_username: blakeNaccarato
project_owner_name: Blake Naccarato
year_of_project_creation: 2021
