# See https://flit.readthedocs.io/en/latest/pyproject_toml.html for more fields.

[build-system]
requires = ["flit_core >=3.3,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dummy"
readme = "README.md"
authors = [{name = "Blake Naccarato", email = "dummy@dummy.dummy"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/blakeNaccarato/tooling"
