"""Short description of the `pytest` tests for your project.

Long description of the `pytest` tests for your project.
"""

import dummy


def test_example():
    """Short description of this test.

    Long description of this test.

    This is an example test generated by the Copier template. As you write code in
    `src/dummy`, you should also write tests. This one is a toy example
    that checks whether your import is the same as the name you supplied to Copier.
    """

    assert dummy.__name__ == "dummy"
