name: "main"

on: ["push", "workflow_dispatch"]

jobs:
  # * ------------------------------------------------------------------------------ * #
  # * Changes below may be lost in significant template updates.

  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.11"
      - run: "pyright"
  pytest-cov:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "copier-python-workflow-setup@v0.0.12"
        with:
          python-version: "3.11"
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.1"

  # * ------------------------------------------------------------------------------ * #
  # * Changes below should persist in significant template updates.
