name: "main"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "dorny/paths-filter@v2"
        with:
          filters: |
            template:
              - "template/**"
  bump_template:
    needs: "changes"
    if: "${{ needs.changes.outputs.template == 'true' }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - run: >-
          python -m pip install -U pip
          pip install -U setuptools wheel
          pip install copier
          copier -f
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Bump `copier-python` template"
  flake8:
    needs: "bump_template"
    if: "${{ always() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.7"
        with:
          python-version: "3.11"
      - run: "flake8"

  pyright:
    needs: "bump_template"
    if: "${{ always() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.7"
        with:
          python-version: "3.11"
      - run: "pyright"

  pytest-cov:
    needs: "bump_template"
    if: "${{ always() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.7"
        with:
          python-version: "3.11"
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.1"
