name: "main"

on: ["workflow_dispatch", "push"]

jobs:
  changes:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "dorny/paths-filter@v2"
        id: "filter"
        with:
          filters: |
            project:
              - "requirements.txt"
              - ".tools/pyproject.toml"
              - .tools/scripts/bump_pyproject.py
            template:
              - "template/**"
    outputs:
      template: "${{ steps.filter.outputs.template }}"
  bump_project:
    needs: "changes"
    if: "${{ needs.changes.outputs.project == 'true' }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - run: |-
          python -m pip install -U pip
          pip install -U setuptools wheel
          pip install toml
          python .tools/scripts/bump_pyproject.py
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Update project"
  bump_template:
    needs: ["changes", "bump_project"]
    if: "${{ needs.changes.outputs.template == 'true' }} && ${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.11"
      - run: |-
          python -m pip install -U pip
          pip install -U setuptools wheel
          pip install copier
          copier -f -r $(git rev-parse HEAD:template)
      - uses: "stefanzweifel/git-auto-commit-action@v4"
        with:
          commit_message: "Update repo to latest template"
  isort:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "isort --check-only ."
  ruff:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "ruff check --no-fix ."
  pyright:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "pyright"
  pytest-cov:
    needs: "bump_template"
    if: "${{ !failure() }}"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "blakeNaccarato/copier-python-workflow-setup@v0.0.11"
        with:
          python-version: "3.11"
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.1"
