name: "main"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  flake8:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "./.github/workflows/common.yml"
      - run: "flake8"

  pyright:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
        with:
          submodules: true
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - run: "bash .tools/scripts/cicd_setup.sh"
      - run: "pyright"

  pytest-cov:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v4"
        with:
          python-version: "3.10"
      - run: "bash .tools/scripts/cicd_setup.sh"
      - run: "pytest --cov"
      - uses: "codecov/codecov-action@v3.1.1"
