on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: ['docs/**']


jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
